spring.application.name=taskmanagement
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tasksDB
spring.datasource.username=root
spring.datasource.password=Chotu@2929
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true